name: Cron
on:
  schedule:
    # - cron: "0 0 * * 0"
    - cron: "*/5 * * * *"
env:

jobs:
  cron:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: deno task start
        run: deno task start
