- sitename: liquipedia
  calendarID: f784c4b938bab23382fb2347cdf787f5ae454f55895209a45ead16888e3fde23@group.calendar.google.com
  source: https://tl.net/calendar/xml/calendar.xml
- sitename: meetup
  calendarID: f784c4b938bab23382fb2347cdf787f5ae454f55895209a45ead16888e3fde23@group.calendar.google.com
  source: https://www.meetup.com/find/?source=EVENTS&eventType=inPerson&sortField=DATETIME&location=vn--Ho%20Chi%20Minh%20City
- sitename: ticketbox
  calendarID: f784c4b938bab23382fb2347cdf787f5ae454f55895209a45ead16888e3fde23@group.calendar.google.com
  source: https://ticketbox.vn/events/ho-chi-minh