name: Cào sự kiện định kỳ
on: 
  push:
  workflow_dispatch:
  schedule:
    # - cron: "0 0 * * 0" # Mỗi tuần
    - cron: "0 0 * * *" # Mỗi nửa đêm

jobs:
  cron:
    name: Chạy chương trình
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Cài Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x
          
      # - name: Giải mã credentials
      #   env:
      #     GOOGLE_API_DECRYPT_PASSWORDWORD: ${{ secrets.GOOGLE_API_DECRYPT_PASSWORDWORD }}
      #     run: |
      #     cd Code\ hỗ\ trợ/Google\ Calendar/
      #     gpg --batch --yes --decrypt --passphrase="$GOOGLE_API_DECRYPT_PASSWORDWORD" --output credentials.json credentials.json.gpg
      #     gpg --batch --yes --decrypt --passphrase="$GOOGLE_API_DECRYPT_PASSWORDWORD" --output token.json token.json.gpg
      #     cd ../..
          
      - name: 
        env:
          DECRYPT_PASSWORD: ${{ secrets.DECRYPT_PASSWORD }}
        run: deno task start