name: Chạy định kỳ
on: 
  # push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  cron:
    name: Chạy chương trình
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Cài Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x
          
      - name: Giải mã credentials
        env:
          GOOGLE_API_PASSWORD: ${{ secrets.GOOGLE_API_PASSWORD }}
        run: |
          cd Code\ hỗ\ trợ/Google\ Calendar/
          gpg --batch --yes --decrypt --passphrase="$GOOGLE_API_PASSWORD" --output credentials.json credentials.json.gpg
          gpg --batch --yes --decrypt --passphrase="$GOOGLE_API_PASSWORD" --output token.json token.json.gpg
          cd ../..
      
      - name: 
        run: deno task start

      - name: git
        run: |
          git config --global user.email "ganuongphap@gmail.com"
          git config --global user.name "ooker"
          git add -A 
          git commit -m "Lưu cache"
          git push